import type { Report } from "@/backend";
import { createActor } from "@/backend";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { Skeleton } from "@/components/ui/skeleton";
import { cn, formatRelativeTime, formatTimestamp } from "@/lib/utils";
import type { Alert, Train } from "@/types";
import { useActor } from "@caffeineai/core-infrastructure";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  AlertTriangle,
  Bot,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  Clock,
  Download,
  FileText,
  Loader2,
  RefreshCw,
  Shield,
  Sparkles,
  TrendingUp,
  User,
} from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

interface ReportsPageProps {
  train: Train;
  alerts: Alert[];
  onResolveAlert: (id: string) => void;
  onRefresh: () => void;
}

// ── Risk badge ────────────────────────────────────────────────────────────────
function RiskBadge({ level }: { level: "low" | "medium" | "high" }) {
  const map: Record<string, string> = {
    low: "bg-chart-1/15 text-chart-1 border-chart-1/30",
    medium: "bg-chart-2/15 text-chart-2 border-chart-2/30",
    high: "bg-destructive/15 text-destructive border-destructive/30",
  };
  return (
    <Badge className={cn("text-[10px] px-2 border capitalize", map[level])}>
      {level} risk
    </Badge>
  );
}

function deriveRiskLevel(report: Report): "low" | "medium" | "high" {
  const passengers = Number(report.totalPassengers);
  const alerts = Number(report.activeAlerts);
  if (alerts >= 3 || passengers > 380) return "high";
  if (alerts >= 1 || passengers > 300) return "medium";
  return "low";
}

// ── Download helper ───────────────────────────────────────────────────────────
function downloadReportTxt(report: Report) {
  const ts = new Date(Number(report.timestamp) / 1_000_000).toLocaleString(
    "en-IN",
    { dateStyle: "full", timeStyle: "long" },
  );
  const riskLevel = deriveRiskLevel(report);
  const text = [
    "═══════════════════════════════════════════════════════",
    "   RAILWATCH AI MONITORING REPORT",
    "═══════════════════════════════════════════════════════",
    "",
    `Report ID     : ${report.id.toString()}`,
    `Train ID      : ${report.trainId}`,
    `Generated At  : ${ts}`,
    `Generated By  : ${report.adminId}`,
    "AI Model      : Google Gemini",
    `Risk Level    : ${riskLevel.toUpperCase()}`,
    "",
    "───────────────────────────────────────────────────────",
    "METRICS SNAPSHOT",
    "───────────────────────────────────────────────────────",
    `Total Passengers : ${report.totalPassengers.toString()}`,
    `Active Alerts    : ${report.activeAlerts.toString()}`,
    "",
    "───────────────────────────────────────────────────────",
    "GEMINI AI ANALYSIS",
    "───────────────────────────────────────────────────────",
    report.geminiResponse,
    "",
    "═══════════════════════════════════════════════════════",
    "  Generated by RailWatch · Powered by Google Gemini",
    "═══════════════════════════════════════════════════════",
  ].join("\n");

  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `railwatch-report-${report.id.toString()}.txt`;
  a.click();
  URL.revokeObjectURL(url);
  toast.success("Report downloaded", { description: "Saved as .txt file" });
}

// ── Report card ───────────────────────────────────────────────────────────────
function BackendReportCard({
  report,
  index,
}: {
  report: Report;
  index: number;
}) {
  const [expanded, setExpanded] = useState(false);
  const riskLevel = deriveRiskLevel(report);
  const ts = Number(report.timestamp) / 1_000_000;

  return (
    <div
      data-ocid={`reports.report_card.item.${index + 1}`}
      className="rounded-xl border border-border bg-card shadow-elevated overflow-hidden transition-smooth"
    >
      <div className="p-4 space-y-3">
        {/* Header row */}
        <div className="flex items-start gap-3">
          <div className="w-9 h-9 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center shrink-0">
            <Bot className="w-4 h-4 text-primary" />
          </div>
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 flex-wrap">
              <span className="font-display font-semibold text-sm text-foreground">
                AI Report #{report.id.toString()}
              </span>
              <RiskBadge level={riskLevel} />
            </div>
            <div className="flex items-center gap-3 mt-1 flex-wrap">
              <span className="text-[10px] text-muted-foreground flex items-center gap-1">
                <Clock className="w-3 h-3" />
                {formatTimestamp(ts)}
              </span>
              <span className="text-[10px] text-muted-foreground flex items-center gap-1">
                <User className="w-3 h-3" />
                {report.adminId}
              </span>
              <span className="text-[10px] text-muted-foreground flex items-center gap-1">
                <TrendingUp className="w-3 h-3" />
                {report.totalPassengers.toString()} pax ·{" "}
                {report.activeAlerts.toString()} alert(s)
              </span>
            </div>
          </div>
        </div>

        {/* Summary preview */}
        {!expanded && (
          <p className="text-xs text-muted-foreground line-clamp-2 pl-12">
            {report.geminiResponse.slice(0, 200)}
            {report.geminiResponse.length > 200 ? "…" : ""}
          </p>
        )}

        {/* Actions */}
        <div className="flex items-center gap-2 pl-12">
          <Button
            variant="outline"
            size="sm"
            className="h-7 text-xs flex-1"
            data-ocid={`reports.expand_button.item.${index + 1}`}
            onClick={() => setExpanded((v) => !v)}
          >
            {expanded ? (
              <>
                <ChevronUp className="w-3 h-3 mr-1" />
                Collapse
              </>
            ) : (
              <>
                <ChevronDown className="w-3 h-3 mr-1" />
                View Full Report
              </>
            )}
          </Button>
          <Button
            variant="outline"
            size="sm"
            className="h-7 text-xs"
            data-ocid={`reports.download_button.item.${index + 1}`}
            onClick={() => downloadReportTxt(report)}
          >
            <Download className="w-3 h-3" />
          </Button>
        </div>

        {/* Expanded content */}
        {expanded && (
          <div className="border-t border-border pt-3 mt-1 space-y-4">
            <div className="grid grid-cols-2 gap-3">
              <div className="rounded-lg bg-muted/40 border border-border p-3">
                <p className="text-label mb-1">Total Passengers</p>
                <p className="font-mono font-bold text-lg text-foreground">
                  {report.totalPassengers.toString()}
                </p>
              </div>
              <div className="rounded-lg bg-muted/40 border border-border p-3">
                <p className="text-label mb-1">Active Alerts</p>
                <p
                  className={cn(
                    "font-mono font-bold text-lg",
                    Number(report.activeAlerts) > 0
                      ? "text-destructive"
                      : "text-chart-1",
                  )}
                >
                  {report.activeAlerts.toString()}
                </p>
              </div>
            </div>

            <div>
              <p className="text-label mb-2">Gemini AI Analysis</p>
              <div className="rounded-lg bg-muted/30 border border-border p-3">
                <p className="text-xs text-foreground leading-relaxed whitespace-pre-wrap">
                  {report.geminiResponse}
                </p>
              </div>
            </div>

            {/* Audit trail */}
            <div className="rounded-lg border border-border/60 bg-muted/20 p-3">
              <p className="text-label mb-2 flex items-center gap-1.5">
                <Shield className="w-3 h-3" />
                Audit Trail
              </p>
              <div className="space-y-1.5 text-[11px] text-muted-foreground font-mono">
                <div className="flex justify-between">
                  <span>Report ID</span>
                  <span className="text-foreground">
                    {report.id.toString()}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span>Train</span>
                  <span className="text-foreground">{report.trainId}</span>
                </div>
                <div className="flex justify-between">
                  <span>Generated by</span>
                  <span className="text-foreground truncate max-w-[140px]">
                    {report.adminId}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span>Timestamp</span>
                  <span className="text-foreground">
                    {new Date(Number(report.timestamp) / 1_000_000)
                      .toISOString()
                      .replace("T", " ")
                      .slice(0, 19)}
                    Z
                  </span>
                </div>
                <div className="flex justify-between">
                  <span>AI Model</span>
                  <span className="text-primary">Google Gemini</span>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// ── Skeleton loader ────────────────────────────────────────────────────────────
function ReportSkeleton() {
  return (
    <div className="rounded-xl border border-border bg-card p-4 space-y-3">
      <div className="flex items-start gap-3">
        <Skeleton className="w-9 h-9 rounded-lg shrink-0" />
        <div className="flex-1 space-y-2">
          <Skeleton className="h-4 w-32" />
          <Skeleton className="h-3 w-48" />
        </div>
      </div>
      <Skeleton className="h-3 w-full ml-12" />
      <Skeleton className="h-3 w-4/5 ml-12" />
    </div>
  );
}

// ── Main page ─────────────────────────────────────────────────────────────────
export default function ReportsPage({ train }: ReportsPageProps) {
  const { actor, isFetching } = useActor(createActor);
  const queryClient = useQueryClient();

  const {
    data: backendReports,
    isLoading: reportsLoading,
    isError: reportsError,
    refetch,
  } = useQuery<Report[]>({
    queryKey: ["reports"],
    queryFn: async () => {
      if (!actor) return [];
      return actor.getReports();
    },
    enabled: !!actor && !isFetching,
  });

  const generateMutation = useMutation({
    mutationFn: async () => {
      if (!actor) throw new Error("Actor not ready");
      const adminId = "admin"; // resolved via identity in production
      return actor.generateReport({
        trainId: train.id,
        adminId,
      });
    },
    onSuccess: (newReport) => {
      queryClient.setQueryData<Report[]>(["reports"], (prev) =>
        prev ? [newReport, ...prev] : [newReport],
      );
      toast.success("AI Report generated", {
        description: "Gemini AI analysis complete.",
      });
    },
    onError: () => {
      toast.error("Report generation failed", {
        description: "Could not reach the backend. Try again.",
      });
    },
  });

  // Sorted newest-first
  const reports = [...(backendReports ?? [])].sort((a, b) =>
    Number(b.timestamp - a.timestamp),
  );

  const avgRisk =
    reports.length > 0
      ? reports.some((r) => deriveRiskLevel(r) === "high")
        ? "High"
        : reports.some((r) => deriveRiskLevel(r) === "medium")
          ? "Medium"
          : "Low"
      : "—";

  const isGenerating = generateMutation.isPending;

  return (
    <div className="space-y-5">
      {/* Page header */}
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h2 className="font-display font-bold text-lg text-foreground">
            AI Reports
          </h2>
          <p className="text-xs text-muted-foreground">
            Powered by Google Gemini ·{" "}
            {reportsLoading ? "Loading…" : `${reports.length} report(s)`}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            className="h-8 gap-1.5"
            data-ocid="reports.refresh_button"
            onClick={() => refetch()}
            disabled={reportsLoading}
          >
            <RefreshCw
              className={cn("w-3.5 h-3.5", reportsLoading && "animate-spin")}
            />
            Refresh
          </Button>
          <Button
            className="gap-2"
            data-ocid="reports.generate_button"
            onClick={() => generateMutation.mutate()}
            disabled={isGenerating || !actor || isFetching}
          >
            {isGenerating ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Generating…
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4" />
                Generate AI Report
              </>
            )}
          </Button>
        </div>
      </div>

      {/* Generation progress indicator */}
      {isGenerating && (
        <div
          data-ocid="reports.loading_state"
          className="rounded-xl border border-primary/20 bg-primary/5 p-4 space-y-3"
        >
          <div className="flex items-center gap-3">
            <Bot className="w-5 h-5 text-primary animate-pulse" />
            <div className="flex-1 space-y-2">
              <p className="text-sm font-medium text-foreground">
                Gemini AI analyzing train data…
              </p>
              <div className="space-y-1.5">
                {[
                  "Collecting real-time occupancy data",
                  "Running safety assessment via HTTP outcall",
                  "Generating executive recommendations",
                ].map((step) => (
                  <div
                    key={step}
                    className="flex items-center gap-2 text-xs text-muted-foreground"
                  >
                    <Loader2 className="w-3 h-3 animate-spin text-primary" />
                    <span>{step}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
          <Skeleton className="h-1.5 w-full bg-primary/20" />
        </div>
      )}

      {/* Stats row */}
      <div className="grid grid-cols-3 gap-3">
        {[
          {
            label: "Reports Generated",
            value: reports.length.toString(),
            icon: FileText,
          },
          {
            label: "Avg Risk Level",
            value: avgRisk,
            icon: TrendingUp,
          },
          { label: "AI Model", value: "Gemini", icon: Bot },
        ].map((stat) => {
          const Icon = stat.icon;
          return (
            <div
              key={stat.label}
              className="rounded-lg border border-border bg-card p-3 flex items-center gap-3"
            >
              <Icon className="w-4 h-4 text-primary shrink-0" />
              <div className="min-w-0">
                <p className="text-label">{stat.label}</p>
                <p className="font-display font-bold text-sm text-foreground truncate">
                  {stat.value}
                </p>
              </div>
            </div>
          );
        })}
      </div>

      <Separator className="bg-border" />

      {/* Report list */}
      <div className="space-y-3">
        {reportsLoading ? (
          <>
            <ReportSkeleton />
            <ReportSkeleton />
          </>
        ) : reportsError ? (
          <div
            data-ocid="reports.error_state"
            className="rounded-xl border border-destructive/30 bg-destructive/5 p-6 flex flex-col items-center gap-3 text-center"
          >
            <AlertTriangle className="w-8 h-8 text-destructive" />
            <div>
              <p className="font-display font-semibold text-foreground">
                Failed to load reports
              </p>
              <p className="text-xs text-muted-foreground mt-1">
                Backend connection error. Check canister deployment.
              </p>
            </div>
            <Button
              variant="outline"
              size="sm"
              onClick={() => refetch()}
              className="mt-1"
            >
              Retry
            </Button>
          </div>
        ) : reports.length === 0 ? (
          <div
            data-ocid="reports.empty_state"
            className="flex flex-col items-center justify-center py-16 gap-4 rounded-xl border border-border bg-card"
          >
            <div className="w-16 h-16 rounded-2xl bg-muted/50 border border-border flex items-center justify-center">
              <FileText className="w-8 h-8 text-muted-foreground" />
            </div>
            <div className="text-center">
              <p className="font-display font-semibold text-foreground">
                No Reports Yet
              </p>
              <p className="text-xs text-muted-foreground mt-1 max-w-xs">
                Click "Generate AI Report" to invoke Gemini and create your
                first executive summary.
              </p>
            </div>
            <Button
              className="gap-2 mt-2"
              data-ocid="reports.empty_generate_button"
              onClick={() => generateMutation.mutate()}
              disabled={isGenerating || !actor || isFetching}
            >
              <Sparkles className="w-4 h-4" />
              Generate First Report
            </Button>
          </div>
        ) : (
          reports.map((report, i) => (
            <BackendReportCard
              key={report.id.toString()}
              report={report}
              index={i}
            />
          ))
        )}
      </div>

      {/* Audit footer */}
      {reports.length > 0 && (
        <div className="rounded-lg border border-border bg-muted/20 p-3 flex items-center justify-between gap-3 flex-wrap">
          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            <Shield className="w-3.5 h-3.5 shrink-0" />
            <span>
              Audit trail: {reports.length} report(s) on record · Last generated{" "}
              {formatRelativeTime(Number(reports[0].timestamp) / 1_000_000)}
            </span>
          </div>
          <div className="flex items-center gap-1.5 text-[10px] text-muted-foreground">
            <CheckCircle2 className="w-3 h-3 text-chart-1" />
            <span>Immutable on Internet Computer</span>
          </div>
        </div>
      )}
    </div>
  );
}
