/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TrainId = IDL.Text;
export const GenerateReportRequest = IDL.Record({
  'trainId' : TrainId,
  'adminId' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const Report = IDL.Record({
  'id' : IDL.Nat,
  'totalPassengers' : IDL.Nat,
  'geminiResponse' : IDL.Text,
  'trainId' : TrainId,
  'activeAlerts' : IDL.Nat,
  'timestamp' : Timestamp,
  'adminId' : IDL.Text,
});
export const CoachId = IDL.Text;
export const AlertSeverity = IDL.Variant({
  'warning' : IDL.Null,
  'critical' : IDL.Null,
});
export const Alert = IDL.Record({
  'id' : IDL.Nat,
  'resolved' : IDL.Bool,
  'description' : IDL.Text,
  'trainId' : TrainId,
  'coachId' : CoachId,
  'timestamp' : Timestamp,
  'severity' : AlertSeverity,
  'resolvedAt' : IDL.Opt(Timestamp),
});
export const OccupancyStatus = IDL.Variant({
  'red' : IDL.Null,
  'green' : IDL.Null,
  'yellow' : IDL.Null,
});
export const CoachOccupancy = IDL.Record({
  'status' : OccupancyStatus,
  'lastUpdated' : Timestamp,
  'totalSeats' : IDL.Nat,
  'coachId' : CoachId,
  'occupiedSeats' : IDL.Nat,
});
export const OccupancySnapshot = IDL.Record({
  'trainId' : TrainId,
  'coaches' : IDL.Vec(CoachOccupancy),
  'timestamp' : Timestamp,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'generateReport' : IDL.Func([GenerateReportRequest], [Report], []),
  'getActiveAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getCoachOccupancies' : IDL.Func([], [IDL.Vec(CoachOccupancy)], ['query']),
  'getOccupancySnapshot' : IDL.Func([], [OccupancySnapshot], ['query']),
  'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'refreshOccupancy' : IDL.Func([], [], []),
  'resolveAlert' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TrainId = IDL.Text;
  const GenerateReportRequest = IDL.Record({
    'trainId' : TrainId,
    'adminId' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const Report = IDL.Record({
    'id' : IDL.Nat,
    'totalPassengers' : IDL.Nat,
    'geminiResponse' : IDL.Text,
    'trainId' : TrainId,
    'activeAlerts' : IDL.Nat,
    'timestamp' : Timestamp,
    'adminId' : IDL.Text,
  });
  const CoachId = IDL.Text;
  const AlertSeverity = IDL.Variant({
    'warning' : IDL.Null,
    'critical' : IDL.Null,
  });
  const Alert = IDL.Record({
    'id' : IDL.Nat,
    'resolved' : IDL.Bool,
    'description' : IDL.Text,
    'trainId' : TrainId,
    'coachId' : CoachId,
    'timestamp' : Timestamp,
    'severity' : AlertSeverity,
    'resolvedAt' : IDL.Opt(Timestamp),
  });
  const OccupancyStatus = IDL.Variant({
    'red' : IDL.Null,
    'green' : IDL.Null,
    'yellow' : IDL.Null,
  });
  const CoachOccupancy = IDL.Record({
    'status' : OccupancyStatus,
    'lastUpdated' : Timestamp,
    'totalSeats' : IDL.Nat,
    'coachId' : CoachId,
    'occupiedSeats' : IDL.Nat,
  });
  const OccupancySnapshot = IDL.Record({
    'trainId' : TrainId,
    'coaches' : IDL.Vec(CoachOccupancy),
    'timestamp' : Timestamp,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'generateReport' : IDL.Func([GenerateReportRequest], [Report], []),
    'getActiveAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getCoachOccupancies' : IDL.Func([], [IDL.Vec(CoachOccupancy)], ['query']),
    'getOccupancySnapshot' : IDL.Func([], [OccupancySnapshot], ['query']),
    'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'refreshOccupancy' : IDL.Func([], [], []),
    'resolveAlert' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };