/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : bigint,
  'resolved' : boolean,
  'description' : string,
  'trainId' : TrainId,
  'coachId' : CoachId,
  'timestamp' : Timestamp,
  'severity' : AlertSeverity,
  'resolvedAt' : [] | [Timestamp],
}
export type AlertSeverity = { 'warning' : null } |
  { 'critical' : null };
export type CoachId = string;
export interface CoachOccupancy {
  'status' : OccupancyStatus,
  'lastUpdated' : Timestamp,
  'totalSeats' : bigint,
  'coachId' : CoachId,
  'occupiedSeats' : bigint,
}
export interface GenerateReportRequest {
  'trainId' : TrainId,
  'adminId' : string,
}
export interface OccupancySnapshot {
  'trainId' : TrainId,
  'coaches' : Array<CoachOccupancy>,
  'timestamp' : Timestamp,
}
export type OccupancyStatus = { 'red' : null } |
  { 'green' : null } |
  { 'yellow' : null };
export interface Report {
  'id' : bigint,
  'totalPassengers' : bigint,
  'geminiResponse' : string,
  'trainId' : TrainId,
  'activeAlerts' : bigint,
  'timestamp' : Timestamp,
  'adminId' : string,
}
export type Timestamp = bigint;
export type TrainId = string;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'generateReport' : ActorMethod<[GenerateReportRequest], Report>,
  'getActiveAlerts' : ActorMethod<[], Array<Alert>>,
  'getAlerts' : ActorMethod<[], Array<Alert>>,
  'getCoachOccupancies' : ActorMethod<[], Array<CoachOccupancy>>,
  'getOccupancySnapshot' : ActorMethod<[], OccupancySnapshot>,
  'getReports' : ActorMethod<[], Array<Report>>,
  'refreshOccupancy' : ActorMethod<[], undefined>,
  'resolveAlert' : ActorMethod<[bigint], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];