/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface CoachOccupancy {
    status: OccupancyStatus;
    lastUpdated: Timestamp;
    totalSeats: bigint;
    coachId: CoachId;
    occupiedSeats: bigint;
}
export interface OccupancySnapshot {
    trainId: TrainId;
    coaches: Array<CoachOccupancy>;
    timestamp: Timestamp;
}
export type TrainId = string;
export interface GenerateReportRequest {
    trainId: TrainId;
    adminId: string;
}
export type CoachId = string;
export interface Report {
    id: bigint;
    totalPassengers: bigint;
    geminiResponse: string;
    trainId: TrainId;
    activeAlerts: bigint;
    timestamp: Timestamp;
    adminId: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Alert {
    id: bigint;
    resolved: boolean;
    description: string;
    trainId: TrainId;
    coachId: CoachId;
    timestamp: Timestamp;
    severity: AlertSeverity;
    resolvedAt?: Timestamp;
}
export enum AlertSeverity {
    warning = "warning",
    critical = "critical"
}
export enum OccupancyStatus {
    red = "red",
    green = "green",
    yellow = "yellow"
}
export interface backendInterface {
    generateReport(req: GenerateReportRequest): Promise<Report>;
    getActiveAlerts(): Promise<Array<Alert>>;
    getAlerts(): Promise<Array<Alert>>;
    getCoachOccupancies(): Promise<Array<CoachOccupancy>>;
    getOccupancySnapshot(): Promise<OccupancySnapshot>;
    getReports(): Promise<Array<Report>>;
    refreshOccupancy(): Promise<void>;
    resolveAlert(alertId: bigint): Promise<boolean>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { Alert as _Alert, AlertSeverity as _AlertSeverity, CoachId as _CoachId, CoachOccupancy as _CoachOccupancy, OccupancySnapshot as _OccupancySnapshot, OccupancyStatus as _OccupancyStatus, Timestamp as _Timestamp, TrainId as _TrainId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async generateReport(arg0: GenerateReportRequest): Promise<Report> {
        if (this.processError) {
            try {
                const result = await this.actor.generateReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateReport(arg0);
            return result;
        }
    }
    async getActiveAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveAlerts();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveAlerts();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlerts();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlerts();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoachOccupancies(): Promise<Array<CoachOccupancy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoachOccupancies();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoachOccupancies();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOccupancySnapshot(): Promise<OccupancySnapshot> {
        if (this.processError) {
            try {
                const result = await this.actor.getOccupancySnapshot();
                return from_candid_OccupancySnapshot_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOccupancySnapshot();
            return from_candid_OccupancySnapshot_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReports(): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReports();
            return result;
        }
    }
    async refreshOccupancy(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.refreshOccupancy();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refreshOccupancy();
            return result;
        }
    }
    async resolveAlert(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveAlert(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_AlertSeverity_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertSeverity): AlertSeverity {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Alert_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Alert): Alert {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_CoachOccupancy_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoachOccupancy): CoachOccupancy {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_OccupancySnapshot_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OccupancySnapshot): OccupancySnapshot {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_OccupancyStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OccupancyStatus): OccupancyStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trainId: _TrainId;
    coaches: Array<_CoachOccupancy>;
    timestamp: _Timestamp;
}): {
    trainId: TrainId;
    coaches: Array<CoachOccupancy>;
    timestamp: Timestamp;
} {
    return {
        trainId: value.trainId,
        coaches: from_candid_vec_n7(_uploadFile, _downloadFile, value.coaches),
        timestamp: value.timestamp
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    resolved: boolean;
    description: string;
    trainId: _TrainId;
    coachId: _CoachId;
    timestamp: _Timestamp;
    severity: _AlertSeverity;
    resolvedAt: [] | [_Timestamp];
}): {
    id: bigint;
    resolved: boolean;
    description: string;
    trainId: TrainId;
    coachId: CoachId;
    timestamp: Timestamp;
    severity: AlertSeverity;
    resolvedAt?: Timestamp;
} {
    return {
        id: value.id,
        resolved: value.resolved,
        description: value.description,
        trainId: value.trainId,
        coachId: value.coachId,
        timestamp: value.timestamp,
        severity: from_candid_AlertSeverity_n4(_uploadFile, _downloadFile, value.severity),
        resolvedAt: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.resolvedAt))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _OccupancyStatus;
    lastUpdated: _Timestamp;
    totalSeats: bigint;
    coachId: _CoachId;
    occupiedSeats: bigint;
}): {
    status: OccupancyStatus;
    lastUpdated: Timestamp;
    totalSeats: bigint;
    coachId: CoachId;
    occupiedSeats: bigint;
} {
    return {
        status: from_candid_OccupancyStatus_n10(_uploadFile, _downloadFile, value.status),
        lastUpdated: value.lastUpdated,
        totalSeats: value.totalSeats,
        coachId: value.coachId,
        occupiedSeats: value.occupiedSeats
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    green: null;
} | {
    yellow: null;
}): OccupancyStatus {
    return "red" in value ? OccupancyStatus.red : "green" in value ? OccupancyStatus.green : "yellow" in value ? OccupancyStatus.yellow : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    warning: null;
} | {
    critical: null;
}): AlertSeverity {
    return "warning" in value ? AlertSeverity.warning : "critical" in value ? AlertSeverity.critical : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Alert>): Array<Alert> {
    return value.map((x)=>from_candid_Alert_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CoachOccupancy>): Array<CoachOccupancy> {
    return value.map((x)=>from_candid_CoachOccupancy_n8(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
